### ISSUE TITLE
make links to source code more obvious

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#10]
looking at a random plugin (e.g. https://studiorack.github.io/studiorack-site/instruments/studiorack/adlplug/adlplug) there is no link to source code, nor any way to verify the build is from you, or how it is packaged or anything at all.

**Comment by RustoMCSpit** [comment]
https://github.com/DISTRHO/Cardinal/issues/653

**Comment by kmturley** [comment]
The link to the source code is already there, but linked from the Author.
I agree it could be made more prominent/obvious.

Adding to enhancements

**Comment by kmturley** [comment]
Add a view source button which makes the link more obvious and easier to review before downloading any plugin:
<img width="1118" alt="Screenshot 2024-07-07 at 9 22 39 PM" src="https://github.com/studiorack/studiorack-site/assets/1710493/ddaae422-177a-435e-a04e-c35096018412">
