### ISSUE TITLE
the site lists a comma at the end of tags

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#16]
"Fx, Instrument," should be "FX, Instrument"

**Comment by RustoMCSpit** [comment]
i think we should try to take inspiration from tonehunt.org and how it presents itself, it does the tags much more cleanly and we can easily take their code as it's MIT

**Comment by kmturley** [comment]
Yes agree comma should not be there.
I do like putting tags as separate chips/pills
<img width="691" alt="Screenshot 2024-04-27 at 9 59 15 PM" src="https://github.com/studiorack/studiorack-site/assets/1710493/fcb83c93-70e8-46c7-85bc-f3fdb813440c">

Adding to list of enhancements
