### ISSUE TITLE
suggestion for new icon-download

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#19]
![bitmap](https://github.com/studiorack/studiorack-site/assets/134429563/9cc93773-8568-4260-85cb-c3d418d74082)

i think the current one is pretty ugly and too small, this one will have to be shrinked but i like its proportions

**Comment by RustoMCSpit** [comment]
oh for some reason it isnt displaying

**Comment by RustoMCSpit** [comment]
i think it should be in a larger rounded square button that has equal distance to the top and side

**Comment by kmturley** [comment]
Looks pretty similar to the existing icon no?
<img width="397" alt="Screenshot 2024-04-27 at 9 50 18 PM" src="https://github.com/studiorack/studiorack-site/assets/1710493/bf3a87ac-04ec-46aa-8b19-1094409b24f0">

I do agree with the comment about the button style though.
All buttons are blue square with rounded corners except this one.
Also this is not technically a download yet, that is on the plugin detail page:
<img width="362" alt="Screenshot 2024-04-27 at 9 51 43 PM" src="https://github.com/studiorack/studiorack-site/assets/1710493/4ea1f413-6093-4b97-be03-7dd3607cefc9">

But these buttons are missing icons.
So will take this as an enhancement to fix this odd difference

**Comment by kmturley** [comment]
Updated design and site with download icons:
<img width="526" alt="Screenshot 2024-07-07 at 9 34 57 PM" src="https://github.com/studiorack/studiorack-site/assets/1710493/23286890-c6b9-473f-ac3e-c2eed4e113bc">
<img width="426" alt="Screenshot 2024-07-07 at 9 34 39 PM" src="https://github.com/studiorack/studiorack-site/assets/1710493/af0cd9c0-089e-46cb-9bf2-5efc940a6df0">
