### ISSUE TITLE
  Consider MPLv2 license

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#22]
Have you considered the MPLv2 license rather than the MIT license?

if you need to know what it's about theres a dicussion here btw https://github.com/SethBling/cbscript/issues/3

**Comment by kmturley** [comment]
This tutorial is good: https://choosealicense.com

Which recommends the most common choice between:
- [MIT License](https://choosealicense.com/licenses/mit/)
- [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/)

They have a deeper comparison of license types here:
https://choosealicense.com/appendix/

I am ok for authors to copy my code and make modifications without making them open-source for now.
If this project gains some adoption and becomes important I would consider GNU GPLv3

So for now, think this is a no!

**Comment by RustoMCSpit** [comment]
hold on, wouldbt you do AGPLv3 as that covers online stuff too
