### ISSUE TITLE
ability to categories synth by wavetable, subtractive, additive, etc.

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#25]

**Comment by kmturley** [comment]
This is possible today for example:
https://studiorack.github.io/studiorack-site/instruments?category=synths&query=additive

Your query is matched against name, description or tags:
https://github.com/studiorack/studiorack-site/blob/main/lib/plugin.ts#L14

You can see that this plugin has additive in the description:
https://studiorack.github.io/studiorack-site/instruments/ryukau/vstplugins/iterative-sin-cluster
