### ISSUE TITLE
glass of water listed twice

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#32]
![image](https://github.com/user-attachments/assets/af0921c1-3d4c-4f43-8300-820b78c56754)

**Comment by kmturley** [comment]
Good spot.

I had added it as yaml:
https://github.com/studiorack/studiorack-registry/tree/main/src/plugins/freepats/glass

But was not able to remove the repo tag:
https://github.com/freepats/glass

And the plugin id there is `freepats/glasses-of-water` so it did not dedupe.

Pushed a fixed to the registry here:
https://github.com/studiorack/studiorack-registry/commit/e42f37d8f25cd4daea79c83b11ce3b851dcd05b1
