### ISSUE TITLE
sort by operating system

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#7]
i use linux so i can only use linux plugins (or windows with yabridge)

**Comment by kmturley** [comment]
Currently all plugins have all binaries.
But in the future this might not be true. Agree this should be a way to filter.
Adding to enhancements

**Comment by RustoMCSpit** [comment]
the plugin title should be bold

**Comment by RustoMCSpit** [comment]
the boxes' padding is too big at the top and too small at the bottom

**Comment by RustoMCSpit** [comment]
> Design for updated filters:
> 
>     * Category
> 
>     * License
> 
>     * Platform
> 
>     * Keyword


https://github.com/studiorack/studiorack-site/issues/18
