### ISSUE TITLE
get rid of discord

### ISSUE THREAD

**Issue by RustoMCSpit** [studiorack/studiorack-site#9]
community chat goes over discord, a proprietary platform which quite some opensource devs have issues with (their terms of service and privacy policy are abysmal)

use revolt https://github.com/revoltchat

**Comment by RustoMCSpit** [comment]
this is why CARDINAL refused (among other reasons) to use studio rack https://github.com/DISTRHO/Cardinal/issues/653

**Comment by kmturley** [comment]
All the audioe communities I am part of use Discord:

1. sfizz
2. sfz
3. Audio Programmer
4. Owlplug

I signed up to revolt and looked for communities and couldn't find any audio ones. It could have potential, but right now it doesn't make sense to adopt.

Saying no to this request for now

**Comment by falkTX** [comment]
why did you try revolt in particular?
first time I hear of it

honestly and sadly the chat world is a big mess right now. used to be better when IRC and matrix were bridged together but there were complications with that.
some people stick to IRC, some have moved on to matrix, some dont care at all and just stick with the big proprietary platforms, with some minorities having their own custom chat system in place

for me discord for chat is akin to be using facebook for a project homepage. it really just doesnt fit what free software culture is supposed to be about.
discord already started its enshittification process, as they need to generate revenue, so at some point it might get shitty enough that people migrate to whatever other popular thing appears and the whole cycle begins again.

**Comment by RustoMCSpit** [comment]
> why did you try revolt in particular?

i wanted the closest thing to discord as possible so it'd be easier for a community to adopt.

> honestly and sadly the chat world is a big mess right now. used to be better when IRC and matrix were bridged together but there were complications with that.
some people stick to IRC, some have moved on to matrix, some dont care at all and just stick with the big proprietary platforms, with some minorities having their own custom chat system in place

hopefully this is fixed by the fediverse

> for me discord for chat is akin to be using facebook for a project homepage. it really just doesnt fit what free software culture is supposed to be about.
discord already started its enshittification process, as they need to generate revenue, so at some point it might get shitty enough that people migrate to whatever other popular thing appears and the whole cycle begins again.

hopefully, just like reddit and lemmy

**Comment by kmturley** [comment]
If you have suggestions for alternatives. I'm always open to ideas and improvements.

I agree Discord is going down the path of commercialization.

**Comment by RustoMCSpit** [comment]
> If you have suggestions for alternatives. I'm always open to ideas and improvements.
> 
> I agree Discord is going down the path of commercialization.

again, revolt is the logical one. you cant get people to use element or matrix

**Comment by falkTX** [comment]
> again, revolt is the logical one. you cant get people to use element or matrix

revolt is not federated, meaning yet another account. so from the first glance it does not seem that different from mattermost or rocketchat systems.

and matrix is already the chat system of choice for big teams like mozilla, gnome and kde. I am on there too, though for now only on the chat.sonoj.com server.

**Comment by RustoMCSpit** [comment]
> > again, revolt is the logical one. you cant get people to use element or matrix
> 
> revolt is not federated, meaning yet another account. so from the first glance it does not seem that different from mattermost or rocketchat systems.
> 
> and matrix is already the chat system of choice for big teams like mozilla, gnome and kde. I am on there too, though for now only on the chat.sonoj.com server.

i think federation is coming? or self-hosting at least? maybe check issues

**Comment by RustoMCSpit** [comment]
just asked
federation most likely wont come but you can self host

**Comment by RustoMCSpit** [comment]
alright then, the decision is matrix or revolt. i think revolt's ui is more familiar, allowing for easier adoption. but no federation is a big deal

**Comment by RustoMCSpit** [comment]
https://developers.revolt.chat/faq/federation

**Comment by RustoMCSpit** [comment]
their reasoning is as follows: We don't think federation is beneficial to Revolt and would actively hinder our stance on privacy. In short, federation is prone to leaking your metadata, could make removing your data harder, and we otherwise have no incentive to develop support if it we aren't able to use it for the main platform (revolt.chat).

**Comment by falkTX** [comment]
how you are making decisions here? I thought studiorack was a project by @kmturley ?

anyhow, I dont have a real answer for chat platforms besides that is all a big mess.
IRC is still around and to this day my main method of communication with other (linux audio) developers, there are some rocketchat, mattermost and revolt groups around, all within their communities, then also matrix for some groups too.
then of course we have others that just prefer convenience over all else and stick with the common platforms even if they are proprietary (we are talking on github after all, so I can fully understand this last point)

for the moment there is no right/correct answer. depending on what chat platform you pick there is always going to be people that will refuse to join there.

**Comment by RustoMCSpit** [comment]
> how you are making decisions here? I thought studiorack was a project by @kmturley ?

im not making decisions
 
> for the moment there is no right/correct answer. depending on what chat platform you pick there is always going to be people that will refuse to join there.

true but theres an ideological richness in choosing the better path

**Comment by falkTX** [comment]
> > how you are making decisions here? I thought studiorack was a project by @kmturley ?
> 
> im not making decisions

that contradicts what you just said:

> alright then, the decision is matrix or revolt

**Comment by RustoMCSpit** [comment]
> > > how you are making decisions here? I thought studiorack was a project by @kmturley ?
> > 
> > 
> > im not making decisions
> 
> that contradicts what you just said:
> 
> > alright then, the decision is matrix or revolt

for him, as there seems to be no other options

**Comment by mxmilkiib** [comment]
Zulip is good, only really apart from the fact you can't order the streams in the sidebar or cluster them yet, though unless you're running a larger server that isn't too much of a problem
